//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GITRepoManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GITRepoManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_Icon {
            get {
                object obj = ResourceManager.GetObject("Browse_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Browse_Icon_Hover {
            get {
                object obj = ResourceManager.GetObject("Browse_Icon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  clone .
        /// </summary>
        internal static string CLONE_REPO_BASE_COMMAND {
            get {
                return ResourceManager.GetString("CLONE_REPO_BASE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the clone repository window.
        /// </summary>
        internal static string CLONE_REPO_COMMAND_INFO {
            get {
                return ResourceManager.GetString("CLONE_REPO_COMMAND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloneIcon {
            get {
                object obj = ResourceManager.GetObject("CloneIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloneIcon_Hover {
            get {
                object obj = ResourceManager.GetObject("CloneIcon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DELETE_REPO_BASE_COMMAND {
            get {
                return ResourceManager.GetString("DELETE_REPO_BASE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a repository to delete.
        /// </summary>
        internal static string DELETE_REPO_BROWSE_HOVER {
            get {
                return ResourceManager.GetString("DELETE_REPO_BROWSE_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the delete repository window.
        /// </summary>
        internal static string DELETE_REPO_COMMAND_INFO {
            get {
                return ResourceManager.GetString("DELETE_REPO_COMMAND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the local clone as well as the repository.
        /// </summary>
        internal static string DELETE_REPO_DELETE_LOCAL_INFO {
            get {
                return ResourceManager.GetString("DELETE_REPO_DELETE_LOCAL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes only the local clone and not the repository.
        /// </summary>
        internal static string DELETE_REPO_IS_CLONE_INFO {
            get {
                return ResourceManager.GetString("DELETE_REPO_IS_CLONE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteIcon {
            get {
                object obj = ResourceManager.GetObject("DeleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteIcon_Hover {
            get {
                object obj = ResourceManager.GetObject("DeleteIcon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GitLogo {
            get {
                object obj = ResourceManager.GetObject("GitLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MOVE_REPO_BASE_COMMAND {
            get {
                return ResourceManager.GetString("MOVE_REPO_BASE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the destination directory for the source repository.
        /// </summary>
        internal static string MOVE_REPO_BROWSE_DESTINATION_INFO {
            get {
                return ResourceManager.GetString("MOVE_REPO_BROWSE_DESTINATION_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the source directory for the repository.
        /// </summary>
        internal static string MOVE_REPO_BROWSE_SOURCE_INFO {
            get {
                return ResourceManager.GetString("MOVE_REPO_BROWSE_SOURCE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the move repository window.
        /// </summary>
        internal static string MOVE_REPO_COMMAND_INFO {
            get {
                return ResourceManager.GetString("MOVE_REPO_COMMAND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveIcon {
            get {
                object obj = ResourceManager.GetObject("MoveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MoveIcon_Hover {
            get {
                object obj = ResourceManager.GetObject("MoveIcon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a bare repository.
        /// </summary>
        internal static string NEW_REPO_BARE_INFO {
            get {
                return ResourceManager.GetString("NEW_REPO_BARE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  init .
        /// </summary>
        internal static string NEW_REPO_BASE_COMMAND {
            get {
                return ResourceManager.GetString("NEW_REPO_BASE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for the desired location to create a repository.
        /// </summary>
        internal static string NEW_REPO_BROWSE_HOVER {
            get {
                return ResourceManager.GetString("NEW_REPO_BROWSE_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the create new repository window.
        /// </summary>
        internal static string NEW_REPO_COMMAND_INFO {
            get {
                return ResourceManager.GetString("NEW_REPO_COMMAND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  --bare .
        /// </summary>
        internal static string NEW_REPO_OPTION_BARE {
            get {
                return ResourceManager.GetString("NEW_REPO_OPTION_BARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  add README.md.
        /// </summary>
        internal static string NEW_REPO_OPTION_README_ADD {
            get {
                return ResourceManager.GetString("NEW_REPO_OPTION_README_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to touch README.md .
        /// </summary>
        internal static string NEW_REPO_OPTION_README_TOUCH {
            get {
                return ResourceManager.GetString("NEW_REPO_OPTION_README_TOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits a README.md to the repository upon creation.
        /// </summary>
        internal static string NEW_REPO_README_INFO {
            get {
                return ResourceManager.GetString("NEW_REPO_README_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewIcon {
            get {
                object obj = ResourceManager.GetObject("NewIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewIcon_Hover {
            get {
                object obj = ResourceManager.GetObject("NewIcon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git.
        /// </summary>
        internal static string REPO_BASE_COMMAND {
            get {
                return ResourceManager.GetString("REPO_BASE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  push -u origin master.
        /// </summary>
        internal static string REPO_PUSH_ORIGIN_MASTER {
            get {
                return ResourceManager.GetString("REPO_PUSH_ORIGIN_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the repository tagging window.
        /// </summary>
        internal static string TAG_REPO_COMMAND_INFO {
            get {
                return ResourceManager.GetString("TAG_REPO_COMMAND_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TagIcon {
            get {
                object obj = ResourceManager.GetObject("TagIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TagIcon_Hover {
            get {
                object obj = ResourceManager.GetObject("TagIcon_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
